spring.application.name=doctor-service

server.port=7079
spring.datasource.username=root
spring.datasource.password=Riya@2001
spring.datasource.url=jdbc:mysql://localhost:3306/mydb

#  local testing--empty all tables--delete--create empty tables--


#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# aws photo upload

aws.accesskey=AKIAU3G3Q5WO5MVCKDPH
aws.secretkey=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
aws.region=ap-south-1
aws.s3.bucket=my-image-bucket-r1
