spring.application.name=payment-service
server.port=7075

# Stripe secret key (never commit real keys)
stripe.secretkey=sk_test_51T3gES4FDa3hpyW3KaNX4egedDi0adS01HKp3POexvLYMVLzfInSUKY1RBZtnRzCTw0eywqo4yJM87fj6OqydTpI00EU2pGT0H

# Disable DB auto config for this microservice
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

stripe.webhook.secret=whsec_fd1a37a84dfdf7465efe986ab34fb0b1dbbc011e335347df4ea7e35a5ad6a2ad