spring.application.name=payment-service
server.port=7075


# Disable DB auto config for this microservice
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Stripe (hidden)
stripe.secretkey=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Booking Service
booking.service.url=${BOOKING_SERVICE_URL}

# Disable DB auto config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Feign Timeout
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=30000

logging.level.com.payment_service.client=DEBUG
