spring.application.name=com.notification-service
server.port=8083
#email------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dhimanria9@gmail.com
spring.mail.password=pivlcpwseitkocdm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#twilio-----sms--whatsapp
twilio.account.sid=AC575e9b7f278b35793ace90b9ffaa3f04
twilio.auth.token=aa8473b395e8c78e9b486412e94f2128
twilio.phone.number=+13509005562
twilio.whatsapp.number=whatsapp:+14155238886

#consumer-kafka connection

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.LongDeserializer

